/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(correlate_symbol_seq_tag_ff.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(14f234cae2651408f2316b172f2ebe6b)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <linecode/correlate_symbol_seq_tag_ff.h>
// pydoc.h is automatically generated in the build directory
#include <correlate_symbol_seq_tag_ff_pydoc.h>

void bind_correlate_symbol_seq_tag_ff(py::module& m)
{

    using correlate_symbol_seq_tag_ff    = gr::linecode::correlate_symbol_seq_tag_ff;


    py::class_<correlate_symbol_seq_tag_ff,
	gr::sync_block,
	gr::block,
	gr::basic_block,
        std::shared_ptr<correlate_symbol_seq_tag_ff>>(m, "correlate_symbol_seq_tag_ff", D(correlate_symbol_seq_tag_ff))

        .def(py::init(&correlate_symbol_seq_tag_ff::make),
           py::arg("symbols"),
           py::arg("threshold"),
           py::arg("tag_name"),
           D(correlate_symbol_seq_tag_ff,make)
        )
        



        ;




}








