/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(diff_manch_dec.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(7c14cf1b4c9acad7d9e7ec08a2ad5dbe)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <linecode/diff_manch_dec.h>
// pydoc.h is automatically generated in the build directory
#include <diff_manch_dec_pydoc.h>

void bind_diff_manch_dec(py::module& m)
{

    using diff_manch_dec    = ::gr::linecode::diff_manch_dec;


    py::class_<diff_manch_dec, gr::sync_decimator,
        std::shared_ptr<diff_manch_dec>>(m, "diff_manch_dec", D(diff_manch_dec))

        .def(py::init(&diff_manch_dec::make),
           py::arg("alignment"),
           D(diff_manch_dec,make)
        )
        



        ;




}








