/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(softuart_rx.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(b918e4caa73698ae46036a860706283e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <linecode/softuart_rx.h>
// pydoc.h is automatically generated in the build directory
#include <softuart_rx_pydoc.h>

void bind_softuart_rx(py::module& m)
{

    using softuart_rx    = ::gr::linecode::softuart_rx;


    py::class_<softuart_rx, gr::block, gr::basic_block,
        std::shared_ptr<softuart_rx>>(m, "softuart_rx", D(softuart_rx))

        .def(py::init(&softuart_rx::make),
           py::arg("samples_per_bit"),
           py::arg("idle_level"),
           py::arg("threshold"),
           py::arg("parity"),
           D(softuart_rx,make)
        )
        



        ;




}








