/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(softuart_tx.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(baabcdf1ccea63ee7a4bd8c6efcd345f)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <linecode/softuart_tx.h>
// pydoc.h is automatically generated in the build directory
#include <softuart_tx_pydoc.h>

void bind_softuart_tx(py::module& m)
{

    using softuart_tx    = ::gr::linecode::softuart_tx;


    py::class_<softuart_tx, gr::block, gr::basic_block,
        std::shared_ptr<softuart_tx>>(m, "softuart_tx", D(softuart_tx))

        .def(py::init(&softuart_tx::make),
           py::arg("samples_per_bit"),
           py::arg("leading_idle_samples"),
           py::arg("parity"),
           D(softuart_tx,make)
        )
        



        ;




}








